/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * keygen.java
 *
 * Created on Mar 8, 2011, 2:39:44 PM
 */

package dcloud;
import java.io.*;
import java.sql.*;
import javax.swing.JOptionPane;
/**
 *
 * @author admin
 */
public class keygen extends javax.swing.JFrame {
public static String ss=accverify.ss;//logged user
    public static String ss1=accverify.ss1;//db name
     public static String ss2=accverify.ss2;//table name
      public static String ss3=accverify.ss4;//file name
      String acc,kk,kr;
    /** Creates new form keygen */
    public keygen() {
        initComponents();
           jTextField1.setText(ss);
        jTextField2.setText(ss1);
        jTextField3.setText(ss2);
       jPanel1.setVisible(false);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jTextField4 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(469, 545));
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "KeyGen", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Maiandra GD", 1, 12), new java.awt.Color(51, 51, 51))); // NOI18N

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dcloud/img/gen.png"))); // NOI18N
        jButton1.setBorderPainted(false);
        jButton1.setContentAreaFilled(false);
        jButton1.setFocusable(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(85, 85, 85)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1);
        jPanel1.setBounds(60, 270, 300, 150);

        jLabel2.setFont(new java.awt.Font("Maiandra GD", 1, 13));
        jLabel2.setText("Logged user");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(70, 90, 210, 60);

        jTextField1.setFont(new java.awt.Font("Maiandra GD", 1, 13));
        jTextField1.setForeground(new java.awt.Color(51, 51, 51));
        getContentPane().add(jTextField1);
        jTextField1.setBounds(260, 100, 139, 30);

        jLabel3.setFont(new java.awt.Font("Maiandra GD", 1, 13));
        jLabel3.setText("Requested user");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(70, 150, 180, 50);

        jLabel4.setFont(new java.awt.Font("Maiandra GD", 1, 13));
        jLabel4.setText("Requested access");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(70, 200, 210, 50);

        jTextField2.setFont(new java.awt.Font("Maiandra GD", 1, 13));
        jTextField2.setForeground(new java.awt.Color(51, 51, 51));
        getContentPane().add(jTextField2);
        jTextField2.setBounds(260, 150, 139, 30);

        jTextField3.setFont(new java.awt.Font("Maiandra GD", 1, 13));
        jTextField3.setForeground(new java.awt.Color(51, 51, 51));
        getContentPane().add(jTextField3);
        jTextField3.setBounds(260, 210, 139, 30);

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dcloud/img/checkbut.png"))); // NOI18N
        jButton2.setBorderPainted(false);
        jButton2.setContentAreaFilled(false);
        jButton2.setFocusable(false);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(100, 450, 150, 40);

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dcloud/img/processbut.png"))); // NOI18N
        jButton3.setBorderPainted(false);
        jButton3.setContentAreaFilled(false);
        jButton3.setFocusable(false);
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3);
        jButton3.setBounds(280, 450, 130, 50);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dcloud/img/keygen.png"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, -20, 520, 570);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
    try
    {
       acc=jTextField3.getText();
       if(acc.equals("first")||acc.equals("second"))
       {
           jPanel1.setVisible(true);



 Class.forName("com.mysql.jdbc.Driver");
      Connection c1 =  DriverManager.getConnection("jdbc:mysql://localhost:3306/ac2","root","");
      Statement stmt1 = c1.createStatement();
      ResultSet rs1=stmt1.executeQuery("select * from temp where user='"+ss1+"'");
      while(rs1.next())
       {
         kk=rs1.getString(5);
         //kr=rs1.getString(2);

 System.out.println(kk);



           }
       }

       else if(acc.equals("third"))
       {
           JOptionPane.showMessageDialog(null, "No keys are needed 2 access the public data");
       }
        }catch(Exception e){

        System.out.println(e.getMessage());
        }


    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed


        jTextField4.setText(kk);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed

        userRetrieve hh=new userRetrieve();
        hh.setVisible(true);

    }//GEN-LAST:event_jButton3ActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new keygen().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    // End of variables declaration//GEN-END:variables

}
