/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * user.java
 *
 * Created on Feb 22, 2011, 5:39:40 PM
 */

package dcloud;

import java.io.*;
import java.sql.*;
import javax.swing.JOptionPane;
import sun.net.www.content.image.png;
/**
 *
 * @author admin
 */
public class user extends javax.swing.JFrame {
public static String id,name,loc,ip;
    /** Creates new form user */
    public user() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jComboBox2 = new javax.swing.JComboBox();
        jLabel4 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(530, 545));
        getContentPane().setLayout(null);

        jLabel2.setFont(new java.awt.Font("Verdana", 1, 14));
        jLabel2.setText("Id");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(30, 120, 80, 30);

        jTextField1.setFont(new java.awt.Font("Verdana", 1, 14));
        getContentPane().add(jTextField1);
        jTextField1.setBounds(200, 120, 140, 30);

        jLabel3.setFont(new java.awt.Font("Verdana", 1, 14));
        jLabel3.setText("Name");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(30, 180, 70, 30);

        jTextField2.setFont(new java.awt.Font("Verdana", 1, 14));
        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField2);
        jTextField2.setBounds(200, 180, 140, 30);

        jLabel5.setFont(new java.awt.Font("Verdana", 1, 14));
        jLabel5.setText("Location");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(30, 320, 70, 20);

        jComboBox2.setBackground(new java.awt.Color(204, 204, 204));
        jComboBox2.setFont(new java.awt.Font("Verdana", 1, 14));
        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "-------------->", "India", "Us", "Australia", "Uk", "China", " " }));
        jComboBox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox2ActionPerformed(evt);
            }
        });
        getContentPane().add(jComboBox2);
        jComboBox2.setBounds(200, 320, 140, 30);

        jLabel4.setFont(new java.awt.Font("Verdana", 1, 14));
        jLabel4.setText("IP Address");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(30, 250, 90, 30);

        jTextField4.setFont(new java.awt.Font("Verdana", 1, 14));
        getContentPane().add(jTextField4);
        jTextField4.setBounds(200, 250, 140, 30);

        jButton1.setBackground(new java.awt.Color(255, 255, 255));
        jButton1.setFont(new java.awt.Font("Verdana", 1, 14));
        jButton1.setText("Submit");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(200, 420, 100, 40);

        jButton2.setBackground(new java.awt.Color(255, 255, 255));
        jButton2.setFont(new java.awt.Font("Verdana", 1, 14));
        jButton2.setText("Redirect");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(320, 420, 110, 40);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dcloud/img/clreg.png"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(-10, -12, 540, 560);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2ActionPerformed

    private void jComboBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        try
        {

            Class.forName("com.mysql.jdbc.Driver");
           Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/3d","root","");
           PreparedStatement ps=con.prepareStatement("insert into user values(?,?,?,?)");
           id=jTextField1.getText();
            name=jTextField2.getText();
            ip=jTextField4.getText();
            loc=jComboBox2.getSelectedItem().toString();
ps.setString(1, id);
ps.setString(2, name);
ps.setString(3, ip);
ps.setString(4, loc);

ps.executeUpdate();

ps.close();
JOptionPane.showMessageDialog(null, "Updated");
jTextField1.setText("");
jTextField2.setText("");
jTextField4.setText("");

        }catch(Exception e){

        System.out.println(e.getMessage());

        }

        

    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed


        pri ii=new pri();
        ii.setVisible(true);

    }//GEN-LAST:event_jButton2ActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new user().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JComboBox jComboBox2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField4;
    // End of variables declaration//GEN-END:variables

}
