/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * userRetrieve.java
 *
 * Created on Mar 8, 2011, 12:55:28 PM
 */

package dcloud;

import javax.swing.JOptionPane;
import java.io.*;
import java.sql.*;
/**
 *
 * @author admin
 */
public class userRetrieve extends javax.swing.JFrame {
 public static String ss=userrequest.ss;
    public static String ss1=userrequest.ss1;
     public static String ss2=userrequest.ss2;
      public static String ss3=userrequest.ss3;
    String kk;
    String kr;
    /** Creates new form userRetrieve */
    public userRetrieve() {
        initComponents();
        jPanel1.setVisible(false);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jButton1 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jTextField1 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(545, 555));
        getContentPane().setLayout(null);

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(10, 100, 280, 400);

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dcloud/img/show.png"))); // NOI18N
        jButton1.setBorderPainted(false);
        jButton1.setContentAreaFilled(false);
        jButton1.setFocusable(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(390, 440, 140, 60);

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Private Key", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Maiandra GD", 1, 12), new java.awt.Color(0, 0, 0))); // NOI18N

        jLabel2.setFont(new java.awt.Font("Maiandra GD", 1, 12));
        jLabel2.setText("Enter the private key 2 Access");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextField1, javax.swing.GroupLayout.DEFAULT_SIZE, 194, Short.MAX_VALUE)
                    .addComponent(jLabel2))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(14, Short.MAX_VALUE)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(57, 57, 57))
        );

        getContentPane().add(jPanel1);
        jPanel1.setBounds(300, 100, 230, 190);

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dcloud/img/checkbut.png"))); // NOI18N
        jButton2.setBorderPainted(false);
        jButton2.setContentAreaFilled(false);
        jButton2.setFocusable(false);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(310, 320, 160, 60);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dcloud/img/useret.png"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 540, 560);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

if(ss2.equals("first")|| ss2.equals("second"))
{

     kr=jTextField1.getText();

try
{

 Class.forName("com.mysql.jdbc.Driver");
      Connection c1 =  DriverManager.getConnection("jdbc:mysql://localhost:3306/ac2","root","");
      Statement stmt1 = c1.createStatement();
      ResultSet rs1=stmt1.executeQuery("select * from temp where user='"+ss1+"'");
      while(rs1.next())
       {
         kk=rs1.getString(5);
         //kr=rs1.getString(2);

 System.out.println(kk);

      }



if(kk.equals(kr))
{
    System.out.println(ss1);
    System.out.println(ss2);
    System.out.println(ss3);
   BufferedReader br1=new BufferedReader(new FileReader("c:\\"+ss1+"\\"+ss2+"\\"+ss3+""));
//BufferedWriter bw1=new BufferedWriter(new FileWriter("c:\\"+aa+"\\LevelC\\"+fnam+""));

String dd;
while((dd=br1.readLine())!=null)
{

    jTextArea1.append(dd+"\n");


 }



}
else
{
JOptionPane.showMessageDialog(null, "not a valid private(ski) value");
          System.out.println("else part");
}



}
catch(Exception e)
{
    System.out.println(e.getMessage());
}
        }


else
{
      try
        {

             Connection cn=DriverManager.getConnection("jdbc:mysql://localhost:3306/"+ss1+"","root","");
                Statement st;
                st=cn.createStatement();
                ResultSet rs=st.executeQuery("select file from "+ss2+" where fname = '"+ss3+"'");

                    while(rs.next())
                    {

String ff=rs.getString(1);
jTextArea1.append(ff+"\n");

 }

}
        catch(Exception e)
        {
            System.out.println(e.getMessage());

        }

}

    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed

        if(ss2.equals("first")|| ss2.equals("second"))
{

             jPanel1.setVisible(true);

        }
        else if(ss2.equals("third"))
        {
            JOptionPane.showMessageDialog(null, "Public Data,No Cipher key is needed");
        }

    }//GEN-LAST:event_jButton2ActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new userRetrieve().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables

}
