/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * userrequest.java
 *
 * Created on Mar 7, 2011, 12:14:58 PM
 */

package dcloud;
import java.io.*;
import java.sql.*;
/**
 *
 * @author admin
 */
public class userrequest extends javax.swing.JFrame {
public static String ss=accverify.ss;//logged user
    public static String ss1=accverify.ss1;//db name
     public static String ss2=accverify.ss2;//table name
      public static String ss3=accverify.ss4;//file name
      String aa[]=new String[100];
      public static String s;
    /** Creates new form userrequest */
    public userrequest() {
        initComponents();
        jTextField1.setText(ss);
        jTextField2.setText(ss1);
        jTextField3.setText(ss2);
        jTextField4.setText(ss3);

    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(539, 552));
        getContentPane().setLayout(null);

        jLabel2.setFont(new java.awt.Font("Maiandra GD", 1, 13));
        jLabel2.setText("Logged user");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(20, 70, 232, 50);

        jLabel3.setFont(new java.awt.Font("Maiandra GD", 1, 13));
        jLabel3.setText("Requested user");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(20, 120, 203, 50);

        jLabel4.setFont(new java.awt.Font("Maiandra GD", 1, 13));
        jLabel4.setText("Requested access");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(20, 160, 232, 50);

        jLabel5.setFont(new java.awt.Font("Maiandra GD", 1, 13));
        jLabel5.setText("Requested file");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(20, 210, 103, 40);

        jTextField1.setFont(new java.awt.Font("Maiandra GD", 1, 13)); // NOI18N
        jTextField1.setForeground(new java.awt.Color(51, 51, 51));
        getContentPane().add(jTextField1);
        jTextField1.setBounds(260, 80, 139, 30);

        jTextField2.setFont(new java.awt.Font("Maiandra GD", 1, 13)); // NOI18N
        jTextField2.setForeground(new java.awt.Color(51, 51, 51));
        getContentPane().add(jTextField2);
        jTextField2.setBounds(260, 130, 139, 30);

        jTextField3.setFont(new java.awt.Font("Maiandra GD", 1, 13)); // NOI18N
        jTextField3.setForeground(new java.awt.Color(51, 51, 51));
        getContentPane().add(jTextField3);
        jTextField3.setBounds(260, 180, 139, 30);

        jTextField4.setFont(new java.awt.Font("Maiandra GD", 1, 13)); // NOI18N
        jTextField4.setForeground(new java.awt.Color(51, 51, 51));
        getContentPane().add(jTextField4);
        jTextField4.setBounds(260, 220, 139, 30);

        jTextArea1.setColumns(20);
        jTextArea1.setFont(new java.awt.Font("Maiandra GD", 1, 13));
        jTextArea1.setForeground(new java.awt.Color(51, 51, 51));
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(10, 270, 370, 230);

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dcloud/img/retbut.png"))); // NOI18N
        jButton1.setBorderPainted(false);
        jButton1.setContentAreaFilled(false);
        jButton1.setFocusable(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(390, 330, 140, 60);

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dcloud/img/processbut.png"))); // NOI18N
        jButton2.setBorderPainted(false);
        jButton2.setContentAreaFilled(false);
        jButton2.setFocusable(false);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(400, 460, 120, 60);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dcloud/img/req2server1.png"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, -10, 540, 570);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed


        try
        {

             Connection cn=DriverManager.getConnection("jdbc:mysql://localhost:3306/"+ss1+"","root","");
                Statement st;
                st=cn.createStatement();
                ResultSet rs=st.executeQuery("select file from "+ss2+" where fname = '"+ss3+"'");

                    while(rs.next())
                    {

String ff=rs.getString(1);
jTextArea1.append(ff+"\n");






                     }





        }
        catch(Exception e)
        {
            System.out.println(e.getMessage());

        }

s= jTextArea1.getText();
System.out.println(s);

    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed

       keygen dd=new keygen();
        dd.setVisible(true);

    }//GEN-LAST:event_jButton2ActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new userrequest().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    // End of variables declaration//GEN-END:variables

}
